import {
  THEME_KEY_RENAMES,
  THEME_UNMAPPED,
  V2_TOKEN_ALLOWLIST,
} from "./policy.ts";
import {
  collectVarNames,
  extractFirstTopLevelRootBlock,
  parseDeclarations,
  rescopeRootSelectors,
  stripGeneratedBanner,
} from "./parse.ts";

export function buildBanner(params: { sha: string; dirty: boolean }): string {
  const lines = [
    "/* GENERATED FILE — do not edit by hand.",
    "   Generated by scripts/generate-theme.ts from Color The Map's v2 design tokens.",
    "   Regenerate: npm run generate:theme — drift check: npm run generate:theme:check",
    `   Source: color-the-map @ ${params.sha}`,
  ];
  if (params.dirty) {
    lines.push(
      "   WARNING: the CTM checkout had uncommitted changes when this was generated;",
      "   this snapshot may not match the stamped commit.",
    );
  }
  return `${lines.join("\n")} */`;
}

// CTM's generated ladder — colors, role aliases, surface classes, materials —
// taken wholesale, with :host added so the one file styles documents and
// shadow roots alike. The dark block stays class-scoped: dark is a per-surface
// opt-in, never a document default.
export function buildLadderSection(ladderCss: string): string {
  return rescopeRootSelectors(stripGeneratedBanner(ladderCss)).trim();
}

export function buildV2TokensSection(tokensV2Css: string): string {
  const body = extractFirstTopLevelRootBlock(tokensV2Css);
  if (body === null) {
    throw new Error(
      "tokens-v2.css: no top-level :root block found — did its structure change upstream?",
    );
  }
  const decls = new Map(parseDeclarations(body).map((d) => [d.name, d.value]));
  const missing = V2_TOKEN_ALLOWLIST.filter((name) => !decls.has(name));
  if (missing.length > 0) {
    throw new Error(
      `tokens-v2.css: allowlisted tokens missing (renamed upstream?): ${missing.join(", ")}`,
    );
  }
  return [
    ":root,",
    ":host {",
    ...V2_TOKEN_ALLOWLIST.map((name) => `  ${name}: ${decls.get(name)};`),
    "}",
  ].join("\n");
}

// The Tailwind mapping: a palette wipe (so off-ladder classes like stock
// bg-red-600 fail visibly instead of resolving to Tailwind's defaults), then
// pass-through `--x: var(--x)` keys — `inline` makes utilities resolve the
// var at use-site, so they follow the surface-scoped re-binding under the
// dark classes. Everything maps mechanically by its own name (ladder colors,
// shadows, allowlisted v2 tokens); policy.ts lists only the renames and the
// deliberately unmapped tokens.
export function buildThemeSection(params: {
  ladderCss: string;
  tokensV2Css: string;
}): string {
  const colorNames = collectVarNames(params.ladderCss, "--color-");
  const shadowNames = collectVarNames(params.ladderCss, "--shadow-");
  const renamedSources = new Set(THEME_KEY_RENAMES.map(([, source]) => source));
  const v2PassThrough = V2_TOKEN_ALLOWLIST.filter(
    (name) => !THEME_UNMAPPED.has(name) && !renamedSources.has(name),
  );
  const mappings = [
    ...v2PassThrough.map((name) => [name, name] as const),
    ...THEME_KEY_RENAMES,
  ];
  const v2Body = extractFirstTopLevelRootBlock(params.tokensV2Css);
  const declared = new Set([
    ...collectVarNames(params.ladderCss, "--"),
    ...(v2Body === null ? [] : parseDeclarations(v2Body).map((d) => d.name)),
  ]);
  const missing = mappings.filter(([, source]) => !declared.has(source));
  if (missing.length > 0) {
    throw new Error(
      `theme mapping source vars missing (renamed upstream?): ${missing
        .map(([, source]) => source)
        .join(", ")}`,
    );
  }
  return [
    "@theme {",
    "  --color-*: initial;",
    "  --color-white: #ffffff;",
    "  --color-black: #000000;",
    "}",
    "",
    "@theme inline {",
    ...colorNames.map((name) => `  ${name}: var(${name});`),
    ...shadowNames.map((name) => `  ${name}: var(${name});`),
    ...mappings.map(([key, source]) => `  ${key}: var(${source});`),
    "}",
  ].join("\n");
}

export function assembleThemeCss(params: {
  ladderCss: string;
  tokensV2Css: string;
  sha: string;
  dirty: boolean;
}): string {
  return `${[
    buildBanner(params),
    "/* ─── Color ladder, roles, surfaces, materials (tokens-ladder.generated.css) ─── */",
    buildLadderSection(params.ladderCss),
    "/* ─── Curated v2 tokens (tokens-v2.css via scripts/theme/policy.ts) ─── */",
    buildV2TokensSection(params.tokensV2Css),
    "/* ─── Tailwind theme mapping ─── */",
    buildThemeSection(params),
  ].join("\n\n")}\n`;
}
